// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/background.js"
    | "/browserExtensionInterface.js"
    | "/content-script.js"
    | "/popup.html"
  export interface WxtRuntime extends Runtime.Static {
    getURL(path: PublicPath): string;
  }
}
